/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
		extend: {
			colors: {
				"on-background": "#e5e1e6",
				"on-error": "#690005",
				"secondary-fixed-dim": "#a2d800",
				"secondary-fixed": "#bdf52f",
				"on-primary": "#31312c",
				"on-tertiary-fixed-variant": "#3d1bce",
				"on-secondary": "#263500",
				"surface-container-low": "#1b1b1f",
				"inverse-surface": "#e5e1e6",
				"border-subtle": "rgba(138, 138, 153, 0.15)",
				"on-secondary-container": "#445c00",
				"surface-container": "#201f23",
				"primary-fixed-dim": "#c9c6c0",
				"secondary-container": "#a5db00",
				"tertiary-fixed-dim": "#c6bfff",
				"on-tertiary-fixed": "#160066",
				"inverse-primary": "#5f5e59",
				"on-primary-fixed-variant": "#474742",
				"text-secondary": "#8A8A99",
				"on-surface-variant": "#c8c7be",
				"on-primary-container": "#65645f",
				"surface-container-lowest": "#0e0e11",
				"on-primary-fixed": "#1c1c18",
				"surface-tint": "#c9c6c0",
				"outline-variant": "#474740",
				"on-tertiary": "#2800a0",
				"tertiary-fixed": "#e4dfff",
				"surface-bright": "#39393d",
				"primary-container": "#e5e2db",
				surface: "#131317",
				"inverse-on-surface": "#303034",
				"surface-muted": "#121214",
				"surface-dim": "#131317",
				"tertiary-container": "#e4dfff",
				"surface-variant": "#353438",
				error: "#ffb4ab",
				"on-secondary-fixed-variant": "#384e00",
				"on-secondary-fixed": "#141f00",
				"on-surface": "#e5e1e6",
				"primary-fixed": "#e5e2db",
				background: "#131317",
				"error-container": "#93000a",
				"on-error-container": "#ffdad6",
				"surface-container-high": "#2a292d",
				tertiary: "#ffffff",
				"on-tertiary-container": "#5c47ec",
				outline: "#929189",
				primary: "#ffffff",
				"surface-container-highest": "#353438",
				secondary: "#bff832",
			},
			borderRadius: {
				DEFAULT: "0.125rem",
				lg: "0.25rem",
				xl: "0.5rem",
				full: "0.75rem",
			},
			spacing: {
				"element-gap": "2rem",
				"container-max": "800px",
				"margin-safe": "1.5rem",
				"section-gap": "6rem",
				"stack-sm": "0.75rem",
			},
			fontFamily: {
				"body-md": ["Hanken Grotesk", "sans-serif"],
				"headline-lg": ["Literata", "serif"],
				"display-xl": ["Literata", "serif"],
				"headline-lg-mobile": ["Literata", "serif"],
				"label-mono": ["JetBrains Mono", "monospace"],
				"quote-italic": ["Literata", "serif"],
			},
			fontSize: {
				"body-md": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
				"headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
				"display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
				"headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
				"label-mono": ["14px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "400" }],
				"quote-italic": ["24px", { lineHeight: "1.4", fontWeight: "400" }],
			},
		},
	},
  plugins: [],
};